version: "3"
services:
    nginx:
        build:
            context: ./resources/nginx
            dockerfile: Dockerfile
        image: nginx:latest
        container_name: development-web
        ports:
            - 80:80
        volumes:
            - ./sources:/opt/project
            - ./resources/nginx/etc/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./resources/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        links:
            - php
        restart: always
        networks:
            development-network: { aliases: [ web.local ] }

    php:
        build:
            context: ./resources/php
            dockerfile: Dockerfile
        image: php:7.2-fpm
        container_name: development-fpm
        volumes:
            - ./sources:/opt/project
            - ./resources/php/etc/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./resources/php/etc/php/conf.d:/usr/local/etc/php/conf.d:ro
        links:
            - mysql
        restart: always
        networks:
            development-network: { aliases: [ fpm.local ] }

    mysql:
        build:
            context: ./resources/mysql
            dockerfile: Dockerfile
        image: percona:5.7
        container_name: development-dbms
        environment:
            MYSQL_USER: development
            MYSQL_PASSWORD: devmysql
            MYSQL_DATABASE: development
            MYSQL_ROOT_PASSWORD: devmysql
        volumes:
            - mysql-data:/var/lib/mysql
            - ./sources:/opt/project
        ports:
            - 3306:3306
        restart: always
        networks:
            development-network: { aliases: [ dbms.local ] }

volumes:
    mysql-data:
        driver: local

networks:
    development-network:
        driver: bridge
